version: "3"
services:
  memgraph:
    image: memgraph/memgraph:2.2.0
    user: memgraph
    entrypoint: ["/usr/lib/memgraph/memgraph", "--telemetry-enabled=false"]
    ports:
      - "7687:7687"

  data-loader:
    build: ./data_loader
    volumes:
      - ./data_loader:/app
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
    depends_on:
      - memgraph
